### ISSUE TITLE
Incorrect badge places in lower Stud.IP versions

### ISSUE THREAD

**Issue by ferishili** [virtUOS/studip-meeting#409]
**Description:**
When using lower versions of StudIP header badges for recording won't appear correctly at the right. 

**Solution:**
adding following css in meeting.css will solve the issue:
```css
section.meetingcomponent {
...
   .meeting-item-header {
      ...
      h1 {
         flex: 1 0 0;
      }
  }
}
```
